.class public final Lorg/apache/poi/hssf/usermodel/HSSFChart;
.super Ljava/lang/Object;
.source "SourceFile"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFSeries;,
        Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFChartType;
    }
.end annotation


# instance fields
.field private chartRecord:Lorg/apache/poi/hssf/record/chart/ChartRecord;

.field private chartTitleFormat:Lorg/apache/poi/hssf/record/chart/ChartTitleFormatRecord;

.field private chartTitleText:Lorg/apache/poi/hssf/record/chart/SeriesTextRecord;

.field private legendRecord:Lorg/apache/poi/hssf/record/chart/LegendRecord;

.field private series:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List<",
            "Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFSeries;",
            ">;"
        }
    .end annotation
.end field

.field private sheet:Lorg/apache/poi/hssf/usermodel/HSSFSheet;

.field private type:Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFChartType;

.field private valueRanges:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List<",
            "Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;",
            ">;"
        }
    .end annotation
.end field


# direct methods
.method private constructor <init>(Lorg/apache/poi/hssf/usermodel/HSSFSheet;Lorg/apache/poi/hssf/record/chart/ChartRecord;)V
    .locals 1

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    new-instance v0, Ljava/util/ArrayList;

    invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V

    iput-object v0, p0, Lorg/apache/poi/hssf/usermodel/HSSFChart;->valueRanges:Ljava/util/List;

    sget-object v0, Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFChartType;->Unknown:Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFChartType;

    iput-object v0, p0, Lorg/apache/poi/hssf/usermodel/HSSFChart;->type:Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFChartType;

    new-instance v0, Ljava/util/ArrayList;

    invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V

    iput-object v0, p0, Lorg/apache/poi/hssf/usermodel/HSSFChart;->series:Ljava/util/List;

    iput-object p2, p0, Lorg/apache/poi/hssf/usermodel/HSSFChart;->chartRecord:Lorg/apache/poi/hssf/record/chart/ChartRecord;

    iput-object p1, p0, Lorg/apache/poi/hssf/usermodel/HSSFChart;->sheet:Lorg/apache/poi/hssf/usermodel/HSSFSheet;

    return-void
.end method

.method private createAllTextRecord()Lorg/apache/poi/hssf/record/chart/TextRecord;
    .locals 3

    new-instance p0, Lorg/apache/poi/hssf/record/chart/TextRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;-><init>()V

    const/4 v0, 0x2

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setHorizontalAlignment(B)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setVerticalAlignment(B)V

    const/4 v0, 0x1

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setDisplayMode(S)V

    const/4 v1, 0x0

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setRgbColor(I)V

    const/16 v2, -0x25

    invoke-virtual {p0, v2}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setX(I)V

    const/16 v2, -0x3c

    invoke-virtual {p0, v2}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setY(I)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setWidth(I)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setHeight(I)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setAutoColor(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setShowKey(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setShowValue(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setVertical(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setAutoGeneratedText(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setGenerated(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setAutoLabelDeleted(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setAutoBackground(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setRotation(S)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setShowCategoryLabelAsPercentage(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setShowValueAsPercentage(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setShowBubbleSizes(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setShowLabel(Z)V

    const/16 v0, 0x4d

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setIndexOfColorValue(S)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setDataLabelPlacement(S)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setTextRotation(S)V

    return-object p0
.end method

.method private createAreaFormatRecord1()Lorg/apache/poi/hssf/record/chart/AreaFormatRecord;
    .locals 2

    new-instance p0, Lorg/apache/poi/hssf/record/chart/AreaFormatRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/AreaFormatRecord;-><init>()V

    const v0, 0xffffff

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/AreaFormatRecord;->setForegroundColor(I)V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/AreaFormatRecord;->setBackgroundColor(I)V

    const/4 v1, 0x1

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/AreaFormatRecord;->setPattern(S)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/AreaFormatRecord;->setAutomatic(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/AreaFormatRecord;->setInvert(Z)V

    const/16 v0, 0x4e

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/AreaFormatRecord;->setForecolorIndex(S)V

    const/16 v0, 0x4d

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/AreaFormatRecord;->setBackcolorIndex(S)V

    return-object p0
.end method

.method private createAreaFormatRecord2()Lorg/apache/poi/hssf/record/chart/AreaFormatRecord;
    .locals 2

    new-instance p0, Lorg/apache/poi/hssf/record/chart/AreaFormatRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/AreaFormatRecord;-><init>()V

    const v0, 0xc0c0c0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/AreaFormatRecord;->setForegroundColor(I)V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/AreaFormatRecord;->setBackgroundColor(I)V

    const/4 v1, 0x1

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/AreaFormatRecord;->setPattern(S)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/AreaFormatRecord;->setAutomatic(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/AreaFormatRecord;->setInvert(Z)V

    const/16 v0, 0x16

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/AreaFormatRecord;->setForecolorIndex(S)V

    const/16 v0, 0x4f

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/AreaFormatRecord;->setBackcolorIndex(S)V

    return-object p0
.end method

.method private createAxisLineFormatRecord(S)Lorg/apache/poi/hssf/record/chart/AxisLineFormatRecord;
    .locals 0

    new-instance p0, Lorg/apache/poi/hssf/record/chart/AxisLineFormatRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/AxisLineFormatRecord;-><init>()V

    invoke-virtual {p0, p1}, Lorg/apache/poi/hssf/record/chart/AxisLineFormatRecord;->setAxisType(S)V

    return-object p0
.end method

.method private createAxisOptionsRecord()Lorg/apache/poi/hssf/record/chart/AxisOptionsRecord;
    .locals 3

    new-instance p0, Lorg/apache/poi/hssf/record/chart/AxisOptionsRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/AxisOptionsRecord;-><init>()V

    const/16 v0, -0x6fe4

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/AxisOptionsRecord;->setMinimumCategory(S)V

    const/16 v1, -0x702b

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/AxisOptionsRecord;->setMaximumCategory(S)V

    const/4 v1, 0x2

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/AxisOptionsRecord;->setMajorUnitValue(S)V

    const/4 v1, 0x0

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/AxisOptionsRecord;->setMajorUnit(S)V

    const/4 v2, 0x1

    invoke-virtual {p0, v2}, Lorg/apache/poi/hssf/record/chart/AxisOptionsRecord;->setMinorUnitValue(S)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/AxisOptionsRecord;->setMinorUnit(S)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/AxisOptionsRecord;->setBaseUnit(S)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/AxisOptionsRecord;->setCrossingPoint(S)V

    invoke-virtual {p0, v2}, Lorg/apache/poi/hssf/record/chart/AxisOptionsRecord;->setDefaultMinimum(Z)V

    invoke-virtual {p0, v2}, Lorg/apache/poi/hssf/record/chart/AxisOptionsRecord;->setDefaultMaximum(Z)V

    invoke-virtual {p0, v2}, Lorg/apache/poi/hssf/record/chart/AxisOptionsRecord;->setDefaultMajor(Z)V

    invoke-virtual {p0, v2}, Lorg/apache/poi/hssf/record/chart/AxisOptionsRecord;->setDefaultMinorUnit(Z)V

    invoke-virtual {p0, v2}, Lorg/apache/poi/hssf/record/chart/AxisOptionsRecord;->setIsDate(Z)V

    invoke-virtual {p0, v2}, Lorg/apache/poi/hssf/record/chart/AxisOptionsRecord;->setDefaultBase(Z)V

    invoke-virtual {p0, v2}, Lorg/apache/poi/hssf/record/chart/AxisOptionsRecord;->setDefaultCross(Z)V

    invoke-virtual {p0, v2}, Lorg/apache/poi/hssf/record/chart/AxisOptionsRecord;->setDefaultDateSettings(Z)V

    return-object p0
.end method

.method private createAxisParentRecord()Lorg/apache/poi/hssf/record/chart/AxisParentRecord;
    .locals 1

    new-instance p0, Lorg/apache/poi/hssf/record/chart/AxisParentRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/AxisParentRecord;-><init>()V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/AxisParentRecord;->setAxisType(S)V

    const/16 v0, 0x1df

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/AxisParentRecord;->setX(I)V

    const/16 v0, 0xdd

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/AxisParentRecord;->setY(I)V

    const/16 v0, 0xbb3

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/AxisParentRecord;->setWidth(I)V

    const/16 v0, 0xb56

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/AxisParentRecord;->setHeight(I)V

    return-object p0
.end method

.method private createAxisRecord(S)Lorg/apache/poi/hssf/record/chart/AxisRecord;
    .locals 0

    new-instance p0, Lorg/apache/poi/hssf/record/chart/AxisRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/AxisRecord;-><init>()V

    invoke-virtual {p0, p1}, Lorg/apache/poi/hssf/record/chart/AxisRecord;->setAxisType(S)V

    return-object p0
.end method

.method private createAxisRecords(Ljava/util/List;)V
    .locals 3
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/util/List<",
            "Lorg/apache/poi/hssf/record/Record;",
            ">;)V"
        }
    .end annotation

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createAxisParentRecord()Lorg/apache/poi/hssf/record/chart/AxisParentRecord;

    move-result-object v0

    invoke-interface {p1, v0}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createBeginRecord()Lorg/apache/poi/hssf/record/chart/BeginRecord;

    move-result-object v0

    invoke-interface {p1, v0}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    const/4 v0, 0x0

    invoke-direct {p0, v0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createAxisRecord(S)Lorg/apache/poi/hssf/record/chart/AxisRecord;

    move-result-object v1

    invoke-interface {p1, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createBeginRecord()Lorg/apache/poi/hssf/record/chart/BeginRecord;

    move-result-object v1

    invoke-interface {p1, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createCategorySeriesAxisRecord()Lorg/apache/poi/hssf/record/chart/CategorySeriesAxisRecord;

    move-result-object v1

    invoke-interface {p1, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createAxisOptionsRecord()Lorg/apache/poi/hssf/record/chart/AxisOptionsRecord;

    move-result-object v1

    invoke-interface {p1, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createTickRecord1()Lorg/apache/poi/hssf/record/chart/TickRecord;

    move-result-object v1

    invoke-interface {p1, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createEndRecord()Lorg/apache/poi/hssf/record/chart/EndRecord;

    move-result-object v1

    invoke-interface {p1, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    const/4 v1, 0x1

    invoke-direct {p0, v1}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createAxisRecord(S)Lorg/apache/poi/hssf/record/chart/AxisRecord;

    move-result-object v2

    invoke-interface {p1, v2}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createBeginRecord()Lorg/apache/poi/hssf/record/chart/BeginRecord;

    move-result-object v2

    invoke-interface {p1, v2}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createValueRangeRecord()Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;

    move-result-object v2

    invoke-interface {p1, v2}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createTickRecord2()Lorg/apache/poi/hssf/record/chart/TickRecord;

    move-result-object v2

    invoke-interface {p1, v2}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0, v1}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createAxisLineFormatRecord(S)Lorg/apache/poi/hssf/record/chart/AxisLineFormatRecord;

    move-result-object v1

    invoke-interface {p1, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0, v0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createLineFormatRecord(Z)Lorg/apache/poi/hssf/record/chart/LineFormatRecord;

    move-result-object v0

    invoke-interface {p1, v0}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createEndRecord()Lorg/apache/poi/hssf/record/chart/EndRecord;

    move-result-object v0

    invoke-interface {p1, v0}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createPlotAreaRecord()Lorg/apache/poi/hssf/record/chart/PlotAreaRecord;

    move-result-object v0

    invoke-interface {p1, v0}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createFrameRecord2()Lorg/apache/poi/hssf/record/chart/FrameRecord;

    move-result-object v0

    invoke-interface {p1, v0}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createBeginRecord()Lorg/apache/poi/hssf/record/chart/BeginRecord;

    move-result-object v0

    invoke-interface {p1, v0}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createLineFormatRecord2()Lorg/apache/poi/hssf/record/chart/LineFormatRecord;

    move-result-object v0

    invoke-interface {p1, v0}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createAreaFormatRecord2()Lorg/apache/poi/hssf/record/chart/AreaFormatRecord;

    move-result-object v0

    invoke-interface {p1, v0}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createEndRecord()Lorg/apache/poi/hssf/record/chart/EndRecord;

    move-result-object v0

    invoke-interface {p1, v0}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createChartFormatRecord()Lorg/apache/poi/hssf/record/chart/ChartFormatRecord;

    move-result-object v0

    invoke-interface {p1, v0}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createBeginRecord()Lorg/apache/poi/hssf/record/chart/BeginRecord;

    move-result-object v0

    invoke-interface {p1, v0}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createBarRecord()Lorg/apache/poi/hssf/record/chart/BarRecord;

    move-result-object v0

    invoke-interface {p1, v0}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createLegendRecord()Lorg/apache/poi/hssf/record/chart/LegendRecord;

    move-result-object v0

    invoke-interface {p1, v0}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createBeginRecord()Lorg/apache/poi/hssf/record/chart/BeginRecord;

    move-result-object v0

    invoke-interface {p1, v0}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createTextRecord()Lorg/apache/poi/hssf/record/chart/TextRecord;

    move-result-object v0

    invoke-interface {p1, v0}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createBeginRecord()Lorg/apache/poi/hssf/record/chart/BeginRecord;

    move-result-object v0

    invoke-interface {p1, v0}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createLinkedDataRecord()Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;

    move-result-object v0

    invoke-interface {p1, v0}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createEndRecord()Lorg/apache/poi/hssf/record/chart/EndRecord;

    move-result-object v0

    invoke-interface {p1, v0}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createEndRecord()Lorg/apache/poi/hssf/record/chart/EndRecord;

    move-result-object v0

    invoke-interface {p1, v0}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createEndRecord()Lorg/apache/poi/hssf/record/chart/EndRecord;

    move-result-object v0

    invoke-interface {p1, v0}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createEndRecord()Lorg/apache/poi/hssf/record/chart/EndRecord;

    move-result-object p0

    invoke-interface {p1, p0}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    return-void
.end method

.method private createAxisUsedRecord(S)Lorg/apache/poi/hssf/record/chart/AxisUsedRecord;
    .locals 0

    new-instance p0, Lorg/apache/poi/hssf/record/chart/AxisUsedRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/AxisUsedRecord;-><init>()V

    invoke-virtual {p0, p1}, Lorg/apache/poi/hssf/record/chart/AxisUsedRecord;->setNumAxis(S)V

    return-object p0
.end method

.method private createBOFRecord()Lorg/apache/poi/hssf/record/BOFRecord;
    .locals 1

    new-instance p0, Lorg/apache/poi/hssf/record/BOFRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/BOFRecord;-><init>()V

    const/16 v0, 0x258

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/BOFRecord;->setVersion(I)V

    const/16 v0, 0x14

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/BOFRecord;->setType(I)V

    const/16 v0, 0x1cfe

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/BOFRecord;->setBuild(I)V

    const/16 v0, 0x7cd

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/BOFRecord;->setBuildYear(I)V

    const/16 v0, 0x40c9

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/BOFRecord;->setHistoryBitMask(I)V

    const/16 v0, 0x6a

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/BOFRecord;->setRequiredVersion(I)V

    return-object p0
.end method

.method private createBarRecord()Lorg/apache/poi/hssf/record/chart/BarRecord;
    .locals 2

    new-instance p0, Lorg/apache/poi/hssf/record/chart/BarRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/BarRecord;-><init>()V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/BarRecord;->setBarSpace(S)V

    const/16 v1, 0x96

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/BarRecord;->setCategorySpace(S)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/BarRecord;->setHorizontal(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/BarRecord;->setStacked(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/BarRecord;->setDisplayAsPercentage(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/BarRecord;->setShadow(Z)V

    return-object p0
.end method

.method private createBeginRecord()Lorg/apache/poi/hssf/record/chart/BeginRecord;
    .locals 0

    new-instance p0, Lorg/apache/poi/hssf/record/chart/BeginRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/BeginRecord;-><init>()V

    return-object p0
.end method

.method private createCategoriesLinkedDataRecord()Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;
    .locals 12

    new-instance p0, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;-><init>()V

    const/4 v0, 0x2

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->setLinkType(B)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->setReferenceType(B)V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->setCustomNumberFormat(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->setIndexNumberFmtRecord(S)V

    new-instance v11, Lorg/apache/poi/ss/formula/ptg/Area3DPtg;

    const/4 v2, 0x0

    const/16 v3, 0x1f

    const/4 v4, 0x1

    const/4 v5, 0x1

    const/4 v6, 0x0

    const/4 v7, 0x0

    const/4 v8, 0x0

    const/4 v9, 0x0

    const/4 v10, 0x0

    move-object v1, v11

    invoke-direct/range {v1 .. v10}, Lorg/apache/poi/ss/formula/ptg/Area3DPtg;-><init>(IIIIZZZZI)V

    const/4 v1, 0x1

    new-array v1, v1, [Lorg/apache/poi/ss/formula/ptg/Ptg;

    aput-object v11, v1, v0

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->setFormulaOfLink([Lorg/apache/poi/ss/formula/ptg/Ptg;)V

    return-object p0
.end method

.method private createCategorySeriesAxisRecord()Lorg/apache/poi/hssf/record/chart/CategorySeriesAxisRecord;
    .locals 1

    new-instance p0, Lorg/apache/poi/hssf/record/chart/CategorySeriesAxisRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/CategorySeriesAxisRecord;-><init>()V

    const/4 v0, 0x1

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/CategorySeriesAxisRecord;->setCrossingPoint(S)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/CategorySeriesAxisRecord;->setLabelFrequency(S)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/CategorySeriesAxisRecord;->setTickMarkFrequency(S)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/CategorySeriesAxisRecord;->setValueAxisCrossing(Z)V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/CategorySeriesAxisRecord;->setCrossesFarRight(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/CategorySeriesAxisRecord;->setReversed(Z)V

    return-object p0
.end method

.method private createChartFormatRecord()Lorg/apache/poi/hssf/record/chart/ChartFormatRecord;
    .locals 1

    new-instance p0, Lorg/apache/poi/hssf/record/chart/ChartFormatRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/ChartFormatRecord;-><init>()V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/ChartFormatRecord;->setXPosition(I)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/ChartFormatRecord;->setYPosition(I)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/ChartFormatRecord;->setWidth(I)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/ChartFormatRecord;->setHeight(I)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/ChartFormatRecord;->setVaryDisplayPattern(Z)V

    return-object p0
.end method

.method private createChartRecord(IIII)Lorg/apache/poi/hssf/record/chart/ChartRecord;
    .locals 0

    new-instance p0, Lorg/apache/poi/hssf/record/chart/ChartRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/ChartRecord;-><init>()V

    invoke-virtual {p0, p1}, Lorg/apache/poi/hssf/record/chart/ChartRecord;->setX(I)V

    invoke-virtual {p0, p2}, Lorg/apache/poi/hssf/record/chart/ChartRecord;->setY(I)V

    invoke-virtual {p0, p3}, Lorg/apache/poi/hssf/record/chart/ChartRecord;->setWidth(I)V

    invoke-virtual {p0, p4}, Lorg/apache/poi/hssf/record/chart/ChartRecord;->setHeight(I)V

    return-object p0
.end method

.method private createDataFormatRecord()Lorg/apache/poi/hssf/record/chart/DataFormatRecord;
    .locals 1

    new-instance p0, Lorg/apache/poi/hssf/record/chart/DataFormatRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/DataFormatRecord;-><init>()V

    const/4 v0, -0x1

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/DataFormatRecord;->setPointNumber(S)V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/DataFormatRecord;->setSeriesIndex(S)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/DataFormatRecord;->setSeriesNumber(S)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/DataFormatRecord;->setUseExcel4Colors(Z)V

    return-object p0
.end method

.method private createDefaultTextRecord(S)Lorg/apache/poi/hssf/record/chart/DefaultDataLabelTextPropertiesRecord;
    .locals 0

    new-instance p0, Lorg/apache/poi/hssf/record/chart/DefaultDataLabelTextPropertiesRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/DefaultDataLabelTextPropertiesRecord;-><init>()V

    invoke-virtual {p0, p1}, Lorg/apache/poi/hssf/record/chart/DefaultDataLabelTextPropertiesRecord;->setCategoryDataType(S)V

    return-object p0
.end method

.method private createDimensionsRecord()Lorg/apache/poi/hssf/record/DimensionsRecord;
    .locals 2

    new-instance p0, Lorg/apache/poi/hssf/record/DimensionsRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/DimensionsRecord;-><init>()V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/DimensionsRecord;->setFirstRow(I)V

    const/16 v1, 0x1f

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/DimensionsRecord;->setLastRow(I)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/DimensionsRecord;->setFirstCol(S)V

    const/4 v0, 0x1

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/DimensionsRecord;->setLastCol(S)V

    return-object p0
.end method

.method private createDirectLinkRecord()Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;
    .locals 2

    new-instance p0, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;-><init>()V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->setLinkType(B)V

    const/4 v1, 0x1

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->setReferenceType(B)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->setCustomNumberFormat(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->setIndexNumberFmtRecord(S)V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->setFormulaOfLink([Lorg/apache/poi/ss/formula/ptg/Ptg;)V

    return-object p0
.end method

.method private createEndRecord()Lorg/apache/poi/hssf/record/chart/EndRecord;
    .locals 0

    new-instance p0, Lorg/apache/poi/hssf/record/chart/EndRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/EndRecord;-><init>()V

    return-object p0
.end method

.method private createFontBasisRecord1()Lorg/apache/poi/hssf/record/chart/FontBasisRecord;
    .locals 1

    new-instance p0, Lorg/apache/poi/hssf/record/chart/FontBasisRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/FontBasisRecord;-><init>()V

    const/16 v0, 0x23a0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/FontBasisRecord;->setXBasis(S)V

    const/16 v0, 0x1608

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/FontBasisRecord;->setYBasis(S)V

    const/16 v0, 0xc8

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/FontBasisRecord;->setHeightBasis(S)V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/FontBasisRecord;->setScale(S)V

    const/4 v0, 0x5

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/FontBasisRecord;->setIndexToFontTable(S)V

    return-object p0
.end method

.method private createFontBasisRecord2()Lorg/apache/poi/hssf/record/chart/FontBasisRecord;
    .locals 1

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createFontBasisRecord1()Lorg/apache/poi/hssf/record/chart/FontBasisRecord;

    move-result-object p0

    const/4 v0, 0x6

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/FontBasisRecord;->setIndexToFontTable(S)V

    return-object p0
.end method

.method private createFontIndexRecord(I)Lorg/apache/poi/hssf/record/chart/FontIndexRecord;
    .locals 0

    new-instance p0, Lorg/apache/poi/hssf/record/chart/FontIndexRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/FontIndexRecord;-><init>()V

    int-to-short p1, p1

    invoke-virtual {p0, p1}, Lorg/apache/poi/hssf/record/chart/FontIndexRecord;->setFontIndex(S)V

    return-object p0
.end method

.method private createFrameRecord1()Lorg/apache/poi/hssf/record/chart/FrameRecord;
    .locals 1

    new-instance p0, Lorg/apache/poi/hssf/record/chart/FrameRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/FrameRecord;-><init>()V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/FrameRecord;->setBorderType(S)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/FrameRecord;->setAutoSize(Z)V

    const/4 v0, 0x1

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/FrameRecord;->setAutoPosition(Z)V

    return-object p0
.end method

.method private createFrameRecord2()Lorg/apache/poi/hssf/record/chart/FrameRecord;
    .locals 1

    new-instance p0, Lorg/apache/poi/hssf/record/chart/FrameRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/FrameRecord;-><init>()V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/FrameRecord;->setBorderType(S)V

    const/4 v0, 0x1

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/FrameRecord;->setAutoSize(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/FrameRecord;->setAutoPosition(Z)V

    return-object p0
.end method

.method private createHCenterRecord()Lorg/apache/poi/hssf/record/HCenterRecord;
    .locals 1

    new-instance p0, Lorg/apache/poi/hssf/record/HCenterRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/HCenterRecord;-><init>()V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/HCenterRecord;->setHCenter(Z)V

    return-object p0
.end method

.method private createLegendRecord()Lorg/apache/poi/hssf/record/chart/LegendRecord;
    .locals 1

    new-instance p0, Lorg/apache/poi/hssf/record/chart/LegendRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/LegendRecord;-><init>()V

    const/16 v0, 0xdd6

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LegendRecord;->setXAxisUpperLeft(I)V

    const/16 v0, 0x61e

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LegendRecord;->setYAxisUpperLeft(I)V

    const/16 v0, 0x1b5

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LegendRecord;->setXSize(I)V

    const/16 v0, 0xd5

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LegendRecord;->setYSize(I)V

    const/4 v0, 0x3

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LegendRecord;->setType(B)V

    const/4 v0, 0x1

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LegendRecord;->setSpacing(B)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LegendRecord;->setAutoPosition(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LegendRecord;->setAutoSeries(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LegendRecord;->setAutoXPositioning(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LegendRecord;->setAutoYPositioning(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LegendRecord;->setVertical(Z)V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LegendRecord;->setDataTable(Z)V

    return-object p0
.end method

.method private createLineFormatRecord(Z)Lorg/apache/poi/hssf/record/chart/LineFormatRecord;
    .locals 1

    new-instance p0, Lorg/apache/poi/hssf/record/chart/LineFormatRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/LineFormatRecord;-><init>()V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LineFormatRecord;->setLineColor(I)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LineFormatRecord;->setLinePattern(S)V

    const/4 v0, -0x1

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LineFormatRecord;->setWeight(S)V

    const/4 v0, 0x1

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LineFormatRecord;->setAuto(Z)V

    invoke-virtual {p0, p1}, Lorg/apache/poi/hssf/record/chart/LineFormatRecord;->setDrawTicks(Z)V

    const/16 p1, 0x4d

    invoke-virtual {p0, p1}, Lorg/apache/poi/hssf/record/chart/LineFormatRecord;->setColourPaletteIndex(S)V

    return-object p0
.end method

.method private createLineFormatRecord2()Lorg/apache/poi/hssf/record/chart/LineFormatRecord;
    .locals 1

    new-instance p0, Lorg/apache/poi/hssf/record/chart/LineFormatRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/LineFormatRecord;-><init>()V

    const v0, 0x808080

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LineFormatRecord;->setLineColor(I)V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LineFormatRecord;->setLinePattern(S)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LineFormatRecord;->setWeight(S)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LineFormatRecord;->setAuto(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LineFormatRecord;->setDrawTicks(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LineFormatRecord;->setUnknown(Z)V

    const/16 v0, 0x17

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LineFormatRecord;->setColourPaletteIndex(S)V

    return-object p0
.end method

.method private createLinkedDataRecord()Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;
    .locals 2

    new-instance p0, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;-><init>()V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->setLinkType(B)V

    const/4 v1, 0x1

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->setReferenceType(B)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->setCustomNumberFormat(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->setIndexNumberFmtRecord(S)V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->setFormulaOfLink([Lorg/apache/poi/ss/formula/ptg/Ptg;)V

    return-object p0
.end method

.method private createMSDrawingObjectRecord()Lorg/apache/poi/hssf/record/UnknownRecord;
    .locals 2

    const/16 p0, 0xc8

    new-array p0, p0, [B

    fill-array-data p0, :array_0

    new-instance v0, Lorg/apache/poi/hssf/record/UnknownRecord;

    const/16 v1, 0xec

    invoke-direct {v0, v1, p0}, Lorg/apache/poi/hssf/record/UnknownRecord;-><init>(I[B)V

    return-object v0

    nop

    :array_0
    .array-data 1
        0xft
        0x0t
        0x2t
        -0x10t
        -0x40t
        0x0t
        0x0t
        0x0t
        0x10t
        0x0t
        0x8t
        -0x10t
        0x8t
        0x0t
        0x0t
        0x0t
        0x2t
        0x0t
        0x0t
        0x0t
        0x2t
        0x4t
        0x0t
        0x0t
        0xft
        0x0t
        0x3t
        -0x10t
        -0x58t
        0x0t
        0x0t
        0x0t
        0xft
        0x0t
        0x4t
        -0x10t
        0x28t
        0x0t
        0x0t
        0x0t
        0x1t
        0x0t
        0x9t
        -0x10t
        0x10t
        0x0t
        0x0t
        0x0t
        0x0t
        0x0t
        0x0t
        0x0t
        0x0t
        0x0t
        0x0t
        0x0t
        0x0t
        0x0t
        0x0t
        0x0t
        0x0t
        0x0t
        0x0t
        0x0t
        0x2t
        0x0t
        0xat
        -0x10t
        0x8t
        0x0t
        0x0t
        0x0t
        0x0t
        0x4t
        0x0t
        0x0t
        0x5t
        0x0t
        0x0t
        0x0t
        0xft
        0x0t
        0x4t
        -0x10t
        0x70t
        0x0t
        0x0t
        0x0t
        -0x6et
        0xct
        0xat
        -0x10t
        0x8t
        0x0t
        0x0t
        0x0t
        0x2t
        0x4t
        0x0t
        0x0t
        0x0t
        0xat
        0x0t
        0x0t
        -0x6dt
        0x0t
        0xbt
        -0x10t
        0x36t
        0x0t
        0x0t
        0x0t
        0x7ft
        0x0t
        0x4t
        0x1t
        0x4t
        0x1t
        -0x41t
        0x0t
        0x8t
        0x0t
        0x8t
        0x0t
        -0x7ft
        0x1t
        0x4et
        0x0t
        0x0t
        0x8t
        -0x7dt
        0x1t
        0x4dt
        0x0t
        0x0t
        0x8t
        -0x41t
        0x1t
        0x10t
        0x0t
        0x11t
        0x0t
        -0x40t
        0x1t
        0x4dt
        0x0t
        0x0t
        0x8t
        -0x1t
        0x1t
        0x8t
        0x0t
        0x8t
        0x0t
        0x3ft
        0x2t
        0x0t
        0x0t
        0x2t
        0x0t
        -0x41t
        0x3t
        0x0t
        0x0t
        0x8t
        0x0t
        0x0t
        0x0t
        0x10t
        -0x10t
        0x12t
        0x0t
        0x0t
        0x0t
        0x0t
        0x0t
        0x4t
        0x0t
        -0x40t
        0x2t
        0xat
        0x0t
        -0xct
        0x0t
        0xet
        0x0t
        0x66t
        0x1t
        0x20t
        0x0t
        -0x17t
        0x0t
        0x0t
        0x0t
        0x11t
        -0x10t
        0x0t
        0x0t
        0x0t
        0x0t
    .end array-data
.end method

.method private createOBJRecord()Lorg/apache/poi/hssf/record/UnknownRecord;
    .locals 2

    const/16 p0, 0x1a

    new-array p0, p0, [B

    fill-array-data p0, :array_0

    new-instance v0, Lorg/apache/poi/hssf/record/UnknownRecord;

    const/16 v1, 0x5d

    invoke-direct {v0, v1, p0}, Lorg/apache/poi/hssf/record/UnknownRecord;-><init>(I[B)V

    return-object v0

    nop

    :array_0
    .array-data 1
        0x15t
        0x0t
        0x12t
        0x0t
        0x5t
        0x0t
        0x2t
        0x0t
        0x11t
        0x60t
        0x0t
        0x0t
        0x0t
        0x0t
        -0x48t
        0x3t
        -0x79t
        0x3t
        0x0t
        0x0t
        0x0t
        0x0t
        0x0t
        0x0t
        0x0t
        0x0t
    .end array-data
.end method

.method private createPlotAreaRecord()Lorg/apache/poi/hssf/record/chart/PlotAreaRecord;
    .locals 0

    new-instance p0, Lorg/apache/poi/hssf/record/chart/PlotAreaRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/PlotAreaRecord;-><init>()V

    return-object p0
.end method

.method private createPlotGrowthRecord(II)Lorg/apache/poi/hssf/record/chart/PlotGrowthRecord;
    .locals 0

    new-instance p0, Lorg/apache/poi/hssf/record/chart/PlotGrowthRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/PlotGrowthRecord;-><init>()V

    invoke-virtual {p0, p1}, Lorg/apache/poi/hssf/record/chart/PlotGrowthRecord;->setHorizontalScale(I)V

    invoke-virtual {p0, p2}, Lorg/apache/poi/hssf/record/chart/PlotGrowthRecord;->setVerticalScale(I)V

    return-object p0
.end method

.method private createPrintSetupRecord()Lorg/apache/poi/hssf/record/PrintSetupRecord;
    .locals 2

    new-instance p0, Lorg/apache/poi/hssf/record/PrintSetupRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/PrintSetupRecord;-><init>()V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/PrintSetupRecord;->setPaperSize(S)V

    const/16 v1, 0x12

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/PrintSetupRecord;->setScale(S)V

    const/4 v1, 0x1

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/PrintSetupRecord;->setPageStart(S)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/PrintSetupRecord;->setFitWidth(S)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/PrintSetupRecord;->setFitHeight(S)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/PrintSetupRecord;->setLeftToRight(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/PrintSetupRecord;->setLandscape(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/PrintSetupRecord;->setValidSettings(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/PrintSetupRecord;->setNoColor(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/PrintSetupRecord;->setDraft(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/PrintSetupRecord;->setNotes(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/PrintSetupRecord;->setNoOrientation(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/PrintSetupRecord;->setUsePage(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/PrintSetupRecord;->setHResolution(S)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/PrintSetupRecord;->setVResolution(S)V

    const-wide/high16 v0, 0x3fe0000000000000L    # 0.5

    invoke-virtual {p0, v0, v1}, Lorg/apache/poi/hssf/record/PrintSetupRecord;->setHeaderMargin(D)V

    invoke-virtual {p0, v0, v1}, Lorg/apache/poi/hssf/record/PrintSetupRecord;->setFooterMargin(D)V

    const/16 v0, 0xf

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/PrintSetupRecord;->setCopies(S)V

    return-object p0
.end method

.method private createSCLRecord(SS)Lorg/apache/poi/hssf/record/SCLRecord;
    .locals 0

    new-instance p0, Lorg/apache/poi/hssf/record/SCLRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/SCLRecord;-><init>()V

    invoke-virtual {p0, p2}, Lorg/apache/poi/hssf/record/SCLRecord;->setDenominator(S)V

    invoke-virtual {p0, p1}, Lorg/apache/poi/hssf/record/SCLRecord;->setNumerator(S)V

    return-object p0
.end method

.method private createSeriesIndexRecord(I)Lorg/apache/poi/hssf/record/chart/SeriesIndexRecord;
    .locals 0

    new-instance p0, Lorg/apache/poi/hssf/record/chart/SeriesIndexRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/SeriesIndexRecord;-><init>()V

    int-to-short p1, p1

    invoke-virtual {p0, p1}, Lorg/apache/poi/hssf/record/chart/SeriesIndexRecord;->setIndex(S)V

    return-object p0
.end method

.method private createSeriesRecord()Lorg/apache/poi/hssf/record/chart/SeriesRecord;
    .locals 2

    new-instance p0, Lorg/apache/poi/hssf/record/chart/SeriesRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/SeriesRecord;-><init>()V

    const/4 v0, 0x1

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/SeriesRecord;->setCategoryDataType(S)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/SeriesRecord;->setValuesDataType(S)V

    const/16 v1, 0x20

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/SeriesRecord;->setNumCategories(S)V

    const/16 v1, 0x1f

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/SeriesRecord;->setNumValues(S)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/SeriesRecord;->setBubbleSeriesType(S)V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/SeriesRecord;->setNumBubbleValues(S)V

    return-object p0
.end method

.method private createSeriesToChartGroupRecord()Lorg/apache/poi/hssf/record/chart/SeriesToChartGroupRecord;
    .locals 0

    new-instance p0, Lorg/apache/poi/hssf/record/chart/SeriesToChartGroupRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/SeriesToChartGroupRecord;-><init>()V

    return-object p0
.end method

.method private createSheetPropsRecord()Lorg/apache/poi/hssf/record/chart/SheetPropertiesRecord;
    .locals 2

    new-instance p0, Lorg/apache/poi/hssf/record/chart/SheetPropertiesRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/SheetPropertiesRecord;-><init>()V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/SheetPropertiesRecord;->setChartTypeManuallyFormatted(Z)V

    const/4 v1, 0x1

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/SheetPropertiesRecord;->setPlotVisibleOnly(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/SheetPropertiesRecord;->setDoNotSizeWithWindow(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/SheetPropertiesRecord;->setDefaultPlotDimensions(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/SheetPropertiesRecord;->setAutoPlotArea(Z)V

    return-object p0
.end method

.method private createTextRecord()Lorg/apache/poi/hssf/record/chart/TextRecord;
    .locals 3

    new-instance p0, Lorg/apache/poi/hssf/record/chart/TextRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;-><init>()V

    const/4 v0, 0x2

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setHorizontalAlignment(B)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setVerticalAlignment(B)V

    const/4 v0, 0x1

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setDisplayMode(S)V

    const/4 v1, 0x0

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setRgbColor(I)V

    const/16 v2, -0x25

    invoke-virtual {p0, v2}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setX(I)V

    const/16 v2, -0x3c

    invoke-virtual {p0, v2}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setY(I)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setWidth(I)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setHeight(I)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setAutoColor(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setShowKey(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setShowValue(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setVertical(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setAutoGeneratedText(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setGenerated(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setAutoLabelDeleted(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setAutoBackground(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setRotation(S)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setShowCategoryLabelAsPercentage(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setShowValueAsPercentage(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setShowBubbleSizes(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setShowLabel(Z)V

    const/16 v0, 0x4d

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setIndexOfColorValue(S)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setDataLabelPlacement(S)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setTextRotation(S)V

    return-object p0
.end method

.method private createTickRecord1()Lorg/apache/poi/hssf/record/chart/TickRecord;
    .locals 3

    new-instance p0, Lorg/apache/poi/hssf/record/chart/TickRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/TickRecord;-><init>()V

    const/4 v0, 0x2

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TickRecord;->setMajorTickType(B)V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TickRecord;->setMinorTickType(B)V

    const/4 v1, 0x3

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TickRecord;->setLabelPosition(B)V

    const/4 v1, 0x1

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TickRecord;->setBackground(B)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TickRecord;->setLabelColorRgb(I)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TickRecord;->setZero1(I)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TickRecord;->setZero2(I)V

    const/16 v2, 0x2d

    invoke-virtual {p0, v2}, Lorg/apache/poi/hssf/record/chart/TickRecord;->setZero3(S)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TickRecord;->setAutorotate(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TickRecord;->setAutoTextBackground(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TickRecord;->setRotation(S)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TickRecord;->setAutorotate(Z)V

    const/16 v0, 0x4d

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TickRecord;->setTickColor(S)V

    return-object p0
.end method

.method private createTickRecord2()Lorg/apache/poi/hssf/record/chart/TickRecord;
    .locals 1

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createTickRecord1()Lorg/apache/poi/hssf/record/chart/TickRecord;

    move-result-object p0

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TickRecord;->setZero3(S)V

    return-object p0
.end method

.method private createTitleLinkedDataRecord()Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;
    .locals 2

    new-instance p0, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;-><init>()V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->setLinkType(B)V

    const/4 v1, 0x1

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->setReferenceType(B)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->setCustomNumberFormat(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->setIndexNumberFmtRecord(S)V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->setFormulaOfLink([Lorg/apache/poi/ss/formula/ptg/Ptg;)V

    return-object p0
.end method

.method private createUnitsRecord()Lorg/apache/poi/hssf/record/chart/UnitsRecord;
    .locals 1

    new-instance p0, Lorg/apache/poi/hssf/record/chart/UnitsRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/UnitsRecord;-><init>()V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/UnitsRecord;->setUnits(S)V

    return-object p0
.end method

.method private createUnknownTextRecord()Lorg/apache/poi/hssf/record/chart/TextRecord;
    .locals 3

    new-instance p0, Lorg/apache/poi/hssf/record/chart/TextRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/TextRecord;-><init>()V

    const/4 v0, 0x2

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setHorizontalAlignment(B)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setVerticalAlignment(B)V

    const/4 v0, 0x1

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setDisplayMode(S)V

    const/4 v1, 0x0

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setRgbColor(I)V

    const/16 v2, -0x25

    invoke-virtual {p0, v2}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setX(I)V

    const/16 v2, -0x3c

    invoke-virtual {p0, v2}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setY(I)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setWidth(I)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setHeight(I)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setAutoColor(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setShowKey(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setShowValue(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setVertical(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setAutoGeneratedText(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setGenerated(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setAutoLabelDeleted(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setAutoBackground(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setRotation(S)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setShowCategoryLabelAsPercentage(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setShowValueAsPercentage(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setShowBubbleSizes(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setShowLabel(Z)V

    const/16 v0, 0x4d

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setIndexOfColorValue(S)V

    const/16 v0, 0x2b50

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setDataLabelPlacement(S)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/TextRecord;->setTextRotation(S)V

    return-object p0
.end method

.method private createVCenterRecord()Lorg/apache/poi/hssf/record/VCenterRecord;
    .locals 1

    new-instance p0, Lorg/apache/poi/hssf/record/VCenterRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/VCenterRecord;-><init>()V

    const/4 v0, 0x0

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/VCenterRecord;->setVCenter(Z)V

    return-object p0
.end method

.method private createValueRangeRecord()Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;
    .locals 2

    new-instance p0, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;-><init>()V

    const-wide/16 v0, 0x0

    invoke-virtual {p0, v0, v1}, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;->setMinimumAxisValue(D)V

    invoke-virtual {p0, v0, v1}, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;->setMaximumAxisValue(D)V

    invoke-virtual {p0, v0, v1}, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;->setMajorIncrement(D)V

    invoke-virtual {p0, v0, v1}, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;->setMinorIncrement(D)V

    invoke-virtual {p0, v0, v1}, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;->setCategoryAxisCross(D)V

    const/4 v0, 0x1

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;->setAutomaticMinimum(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;->setAutomaticMaximum(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;->setAutomaticMajor(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;->setAutomaticMinor(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;->setAutomaticCategoryCrossing(Z)V

    const/4 v1, 0x0

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;->setLogarithmicScale(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;->setValuesInReverse(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;->setCrossCategoryAxisAtMaximum(Z)V

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;->setReserved(Z)V

    return-object p0
.end method

.method private createValuesLinkedDataRecord()Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;
    .locals 13

    new-instance p0, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;

    invoke-direct {p0}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;-><init>()V

    const/4 v0, 0x1

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->setLinkType(B)V

    const/4 v1, 0x2

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->setReferenceType(B)V

    const/4 v1, 0x0

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->setCustomNumberFormat(Z)V

    invoke-virtual {p0, v1}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->setIndexNumberFmtRecord(S)V

    new-instance v12, Lorg/apache/poi/ss/formula/ptg/Area3DPtg;

    const/4 v3, 0x0

    const/16 v4, 0x1f

    const/4 v5, 0x0

    const/4 v6, 0x0

    const/4 v7, 0x0

    const/4 v8, 0x0

    const/4 v9, 0x0

    const/4 v10, 0x0

    const/4 v11, 0x0

    move-object v2, v12

    invoke-direct/range {v2 .. v11}, Lorg/apache/poi/ss/formula/ptg/Area3DPtg;-><init>(IIIIZZZZI)V

    new-array v0, v0, [Lorg/apache/poi/ss/formula/ptg/Ptg;

    aput-object v12, v0, v1

    invoke-virtual {p0, v0}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->setFormulaOfLink([Lorg/apache/poi/ss/formula/ptg/Ptg;)V

    return-object p0
.end method

.method public static getSheetCharts(Lorg/apache/poi/hssf/usermodel/HSSFSheet;)[Lorg/apache/poi/hssf/usermodel/HSSFChart;
    .locals 12

    new-instance v0, Ljava/util/ArrayList;

    invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V

    invoke-virtual {p0}, Lorg/apache/poi/hssf/usermodel/HSSFSheet;->getSheet()Lorg/apache/poi/hssf/model/InternalSheet;

    move-result-object v1

    invoke-virtual {v1}, Lorg/apache/poi/hssf/model/InternalSheet;->getRecords()Ljava/util/List;

    move-result-object v1

    invoke-interface {v1}, Ljava/util/List;->iterator()Ljava/util/Iterator;

    move-result-object v1

    const/4 v2, 0x0

    move-object v3, v2

    move-object v4, v3

    :cond_0
    :goto_0
    invoke-interface {v1}, Ljava/util/Iterator;->hasNext()Z

    move-result v5

    if-eqz v5, :cond_b

    invoke-interface {v1}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v5

    check-cast v5, Lorg/apache/poi/hssf/record/RecordBase;

    instance-of v6, v5, Lorg/apache/poi/hssf/record/chart/ChartRecord;

    if-eqz v6, :cond_1

    new-instance v3, Lorg/apache/poi/hssf/usermodel/HSSFChart;

    check-cast v5, Lorg/apache/poi/hssf/record/chart/ChartRecord;

    invoke-direct {v3, p0, v5}, Lorg/apache/poi/hssf/usermodel/HSSFChart;-><init>(Lorg/apache/poi/hssf/usermodel/HSSFSheet;Lorg/apache/poi/hssf/record/chart/ChartRecord;)V

    invoke-interface {v0, v3}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    move-object v4, v2

    goto :goto_0

    :cond_1
    instance-of v6, v5, Lorg/apache/poi/hssf/record/chart/LegendRecord;

    if-eqz v6, :cond_2

    check-cast v5, Lorg/apache/poi/hssf/record/chart/LegendRecord;

    iput-object v5, v3, Lorg/apache/poi/hssf/usermodel/HSSFChart;->legendRecord:Lorg/apache/poi/hssf/record/chart/LegendRecord;

    goto :goto_0

    :cond_2
    instance-of v6, v5, Lorg/apache/poi/hssf/record/chart/SeriesRecord;

    if-eqz v6, :cond_3

    new-instance v4, Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFSeries;

    invoke-virtual {v3}, Ljava/lang/Object;->getClass()Ljava/lang/Class;

    check-cast v5, Lorg/apache/poi/hssf/record/chart/SeriesRecord;

    invoke-direct {v4, v3, v5}, Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFSeries;-><init>(Lorg/apache/poi/hssf/usermodel/HSSFChart;Lorg/apache/poi/hssf/record/chart/SeriesRecord;)V

    iget-object v5, v3, Lorg/apache/poi/hssf/usermodel/HSSFChart;->series:Ljava/util/List;

    invoke-interface {v5, v4}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    goto :goto_0

    :cond_3
    instance-of v6, v5, Lorg/apache/poi/hssf/record/chart/ChartTitleFormatRecord;

    if-eqz v6, :cond_4

    check-cast v5, Lorg/apache/poi/hssf/record/chart/ChartTitleFormatRecord;

    iput-object v5, v3, Lorg/apache/poi/hssf/usermodel/HSSFChart;->chartTitleFormat:Lorg/apache/poi/hssf/record/chart/ChartTitleFormatRecord;

    goto :goto_0

    :cond_4
    instance-of v6, v5, Lorg/apache/poi/hssf/record/chart/SeriesTextRecord;

    if-eqz v6, :cond_6

    check-cast v5, Lorg/apache/poi/hssf/record/chart/SeriesTextRecord;

    iget-object v6, v3, Lorg/apache/poi/hssf/usermodel/HSSFChart;->legendRecord:Lorg/apache/poi/hssf/record/chart/LegendRecord;

    if-nez v6, :cond_5

    iget-object v6, v3, Lorg/apache/poi/hssf/usermodel/HSSFChart;->series:Ljava/util/List;

    invoke-interface {v6}, Ljava/util/List;->size()I

    move-result v6

    if-lez v6, :cond_5

    iget-object v6, v3, Lorg/apache/poi/hssf/usermodel/HSSFChart;->series:Ljava/util/List;

    invoke-interface {v6}, Ljava/util/List;->size()I

    move-result v7

    add-int/lit8 v7, v7, -0x1

    invoke-interface {v6, v7}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v6

    check-cast v6, Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFSeries;

    invoke-static {v6, v5}, Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFSeries;->access$102(Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFSeries;Lorg/apache/poi/hssf/record/chart/SeriesTextRecord;)Lorg/apache/poi/hssf/record/chart/SeriesTextRecord;

    goto :goto_0

    :cond_5
    iput-object v5, v3, Lorg/apache/poi/hssf/usermodel/HSSFChart;->chartTitleText:Lorg/apache/poi/hssf/record/chart/SeriesTextRecord;

    goto :goto_0

    :cond_6
    instance-of v6, v5, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;

    if-eqz v6, :cond_7

    check-cast v5, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;

    if-eqz v4, :cond_0

    invoke-virtual {v4, v5}, Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFSeries;->insertData(Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;)V

    goto :goto_0

    :cond_7
    instance-of v6, v5, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;

    if-eqz v6, :cond_8

    iget-object v6, v3, Lorg/apache/poi/hssf/usermodel/HSSFChart;->valueRanges:Ljava/util/List;

    check-cast v5, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;

    invoke-interface {v6, v5}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    goto/16 :goto_0

    :cond_8
    instance-of v6, v5, Lorg/apache/poi/hssf/record/Record;

    if-eqz v6, :cond_0

    if-eqz v3, :cond_0

    check-cast v5, Lorg/apache/poi/hssf/record/Record;

    invoke-static {}, Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFChartType;->values()[Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFChartType;

    move-result-object v6

    array-length v7, v6

    const/4 v8, 0x0

    :goto_1
    if-ge v8, v7, :cond_0

    aget-object v9, v6, v8

    sget-object v10, Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFChartType;->Unknown:Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFChartType;

    if-ne v9, v10, :cond_9

    goto :goto_2

    :cond_9
    invoke-virtual {v5}, Lorg/apache/poi/hssf/record/Record;->getSid()S

    move-result v10

    invoke-virtual {v9}, Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFChartType;->getSid()S

    move-result v11

    if-ne v10, v11, :cond_a

    iput-object v9, v3, Lorg/apache/poi/hssf/usermodel/HSSFChart;->type:Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFChartType;

    goto/16 :goto_0

    :cond_a
    :goto_2
    add-int/lit8 v8, v8, 0x1

    goto :goto_1

    :cond_b
    invoke-interface {v0}, Ljava/util/List;->size()I

    move-result p0

    new-array p0, p0, [Lorg/apache/poi/hssf/usermodel/HSSFChart;

    invoke-interface {v0, p0}, Ljava/util/List;->toArray([Ljava/lang/Object;)[Ljava/lang/Object;

    move-result-object p0

    check-cast p0, [Lorg/apache/poi/hssf/usermodel/HSSFChart;

    return-object p0
.end method


# virtual methods
.method public createBarChart(Lorg/apache/poi/hssf/usermodel/HSSFWorkbook;Lorg/apache/poi/hssf/usermodel/HSSFSheet;)V
    .locals 5

    new-instance v0, Ljava/util/ArrayList;

    invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createMSDrawingObjectRecord()Lorg/apache/poi/hssf/record/UnknownRecord;

    move-result-object v1

    invoke-interface {v0, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createOBJRecord()Lorg/apache/poi/hssf/record/UnknownRecord;

    move-result-object v1

    invoke-interface {v0, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createBOFRecord()Lorg/apache/poi/hssf/record/BOFRecord;

    move-result-object v1

    invoke-interface {v0, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    new-instance v1, Lorg/apache/poi/hssf/record/HeaderRecord;

    const-string v2, ""

    invoke-direct {v1, v2}, Lorg/apache/poi/hssf/record/HeaderRecord;-><init>(Ljava/lang/String;)V

    invoke-interface {v0, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    new-instance v1, Lorg/apache/poi/hssf/record/FooterRecord;

    invoke-direct {v1, v2}, Lorg/apache/poi/hssf/record/FooterRecord;-><init>(Ljava/lang/String;)V

    invoke-interface {v0, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createHCenterRecord()Lorg/apache/poi/hssf/record/HCenterRecord;

    move-result-object v1

    invoke-interface {v0, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createVCenterRecord()Lorg/apache/poi/hssf/record/VCenterRecord;

    move-result-object v1

    invoke-interface {v0, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createPrintSetupRecord()Lorg/apache/poi/hssf/record/PrintSetupRecord;

    move-result-object v1

    invoke-interface {v0, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createFontBasisRecord1()Lorg/apache/poi/hssf/record/chart/FontBasisRecord;

    move-result-object v1

    invoke-interface {v0, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createFontBasisRecord2()Lorg/apache/poi/hssf/record/chart/FontBasisRecord;

    move-result-object v1

    invoke-interface {v0, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    new-instance v1, Lorg/apache/poi/hssf/record/ProtectRecord;

    const/4 v2, 0x0

    invoke-direct {v1, v2}, Lorg/apache/poi/hssf/record/ProtectRecord;-><init>(Z)V

    invoke-interface {v0, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createUnitsRecord()Lorg/apache/poi/hssf/record/chart/UnitsRecord;

    move-result-object v1

    invoke-interface {v0, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    const v1, 0x1d06658

    const v3, 0x1226640

    invoke-direct {p0, v2, v2, v1, v3}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createChartRecord(IIII)Lorg/apache/poi/hssf/record/chart/ChartRecord;

    move-result-object v1

    invoke-interface {v0, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createBeginRecord()Lorg/apache/poi/hssf/record/chart/BeginRecord;

    move-result-object v1

    invoke-interface {v0, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    const/4 v1, 0x1

    invoke-direct {p0, v1, v1}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createSCLRecord(SS)Lorg/apache/poi/hssf/record/SCLRecord;

    move-result-object v2

    invoke-interface {v0, v2}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    const/high16 v2, 0x10000

    invoke-direct {p0, v2, v2}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createPlotGrowthRecord(II)Lorg/apache/poi/hssf/record/chart/PlotGrowthRecord;

    move-result-object v2

    invoke-interface {v0, v2}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createFrameRecord1()Lorg/apache/poi/hssf/record/chart/FrameRecord;

    move-result-object v2

    invoke-interface {v0, v2}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createBeginRecord()Lorg/apache/poi/hssf/record/chart/BeginRecord;

    move-result-object v2

    invoke-interface {v0, v2}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0, v1}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createLineFormatRecord(Z)Lorg/apache/poi/hssf/record/chart/LineFormatRecord;

    move-result-object v2

    invoke-interface {v0, v2}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createAreaFormatRecord1()Lorg/apache/poi/hssf/record/chart/AreaFormatRecord;

    move-result-object v2

    invoke-interface {v0, v2}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createEndRecord()Lorg/apache/poi/hssf/record/chart/EndRecord;

    move-result-object v2

    invoke-interface {v0, v2}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createSeriesRecord()Lorg/apache/poi/hssf/record/chart/SeriesRecord;

    move-result-object v2

    invoke-interface {v0, v2}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createBeginRecord()Lorg/apache/poi/hssf/record/chart/BeginRecord;

    move-result-object v2

    invoke-interface {v0, v2}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createTitleLinkedDataRecord()Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;

    move-result-object v2

    invoke-interface {v0, v2}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createValuesLinkedDataRecord()Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;

    move-result-object v2

    invoke-interface {v0, v2}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createCategoriesLinkedDataRecord()Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;

    move-result-object v2

    invoke-interface {v0, v2}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createDataFormatRecord()Lorg/apache/poi/hssf/record/chart/DataFormatRecord;

    move-result-object v2

    invoke-interface {v0, v2}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createSeriesToChartGroupRecord()Lorg/apache/poi/hssf/record/chart/SeriesToChartGroupRecord;

    move-result-object v2

    invoke-interface {v0, v2}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createEndRecord()Lorg/apache/poi/hssf/record/chart/EndRecord;

    move-result-object v2

    invoke-interface {v0, v2}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createSheetPropsRecord()Lorg/apache/poi/hssf/record/chart/SheetPropertiesRecord;

    move-result-object v2

    invoke-interface {v0, v2}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    const/4 v2, 0x2

    invoke-direct {p0, v2}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createDefaultTextRecord(S)Lorg/apache/poi/hssf/record/chart/DefaultDataLabelTextPropertiesRecord;

    move-result-object v3

    invoke-interface {v0, v3}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createAllTextRecord()Lorg/apache/poi/hssf/record/chart/TextRecord;

    move-result-object v3

    invoke-interface {v0, v3}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createBeginRecord()Lorg/apache/poi/hssf/record/chart/BeginRecord;

    move-result-object v3

    invoke-interface {v0, v3}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    const/4 v3, 0x5

    invoke-direct {p0, v3}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createFontIndexRecord(I)Lorg/apache/poi/hssf/record/chart/FontIndexRecord;

    move-result-object v3

    invoke-interface {v0, v3}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createDirectLinkRecord()Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;

    move-result-object v3

    invoke-interface {v0, v3}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createEndRecord()Lorg/apache/poi/hssf/record/chart/EndRecord;

    move-result-object v3

    invoke-interface {v0, v3}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    const/4 v3, 0x3

    invoke-direct {p0, v3}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createDefaultTextRecord(S)Lorg/apache/poi/hssf/record/chart/DefaultDataLabelTextPropertiesRecord;

    move-result-object v4

    invoke-interface {v0, v4}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createUnknownTextRecord()Lorg/apache/poi/hssf/record/chart/TextRecord;

    move-result-object v4

    invoke-interface {v0, v4}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createBeginRecord()Lorg/apache/poi/hssf/record/chart/BeginRecord;

    move-result-object v4

    invoke-interface {v0, v4}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    const/4 v4, 0x6

    invoke-direct {p0, v4}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createFontIndexRecord(I)Lorg/apache/poi/hssf/record/chart/FontIndexRecord;

    move-result-object v4

    invoke-interface {v0, v4}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createDirectLinkRecord()Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;

    move-result-object v4

    invoke-interface {v0, v4}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createEndRecord()Lorg/apache/poi/hssf/record/chart/EndRecord;

    move-result-object v4

    invoke-interface {v0, v4}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0, v1}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createAxisUsedRecord(S)Lorg/apache/poi/hssf/record/chart/AxisUsedRecord;

    move-result-object v4

    invoke-interface {v0, v4}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0, v0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createAxisRecords(Ljava/util/List;)V

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createEndRecord()Lorg/apache/poi/hssf/record/chart/EndRecord;

    move-result-object v4

    invoke-interface {v0, v4}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createDimensionsRecord()Lorg/apache/poi/hssf/record/DimensionsRecord;

    move-result-object v4

    invoke-interface {v0, v4}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0, v2}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createSeriesIndexRecord(I)Lorg/apache/poi/hssf/record/chart/SeriesIndexRecord;

    move-result-object v2

    invoke-interface {v0, v2}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0, v1}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createSeriesIndexRecord(I)Lorg/apache/poi/hssf/record/chart/SeriesIndexRecord;

    move-result-object v1

    invoke-interface {v0, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-direct {p0, v3}, Lorg/apache/poi/hssf/usermodel/HSSFChart;->createSeriesIndexRecord(I)Lorg/apache/poi/hssf/record/chart/SeriesIndexRecord;

    move-result-object p0

    invoke-interface {v0, p0}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    sget-object p0, Lorg/apache/poi/hssf/record/EOFRecord;->instance:Lorg/apache/poi/hssf/record/EOFRecord;

    invoke-interface {v0, p0}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    invoke-virtual {p2, v0}, Lorg/apache/poi/hssf/usermodel/HSSFSheet;->insertChartRecords(Ljava/util/List;)V

    invoke-virtual {p1}, Lorg/apache/poi/hssf/usermodel/HSSFWorkbook;->insertChartRecord()V

    return-void
.end method

.method public createSeries()Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFSeries;
    .locals 15
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/lang/Exception;
        }
    .end annotation

    new-instance v0, Ljava/util/ArrayList;

    invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V

    iget-object v1, p0, Lorg/apache/poi/hssf/usermodel/HSSFChart;->sheet:Lorg/apache/poi/hssf/usermodel/HSSFSheet;

    invoke-virtual {v1}, Lorg/apache/poi/hssf/usermodel/HSSFSheet;->getSheet()Lorg/apache/poi/hssf/model/InternalSheet;

    move-result-object v1

    invoke-virtual {v1}, Lorg/apache/poi/hssf/model/InternalSheet;->getRecords()Ljava/util/List;

    move-result-object v1

    invoke-interface {v1}, Ljava/util/List;->iterator()Ljava/util/Iterator;

    move-result-object v2

    const/4 v3, 0x0

    const/4 v4, -0x1

    move v5, v3

    move v6, v5

    move v7, v6

    move v8, v4

    move v9, v8

    move v10, v9

    move v11, v10

    :cond_0
    :goto_0
    invoke-interface {v2}, Ljava/util/Iterator;->hasNext()Z

    move-result v12

    const/4 v13, 0x1

    if-eqz v12, :cond_7

    invoke-interface {v2}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v12

    check-cast v12, Lorg/apache/poi/hssf/record/RecordBase;

    add-int/2addr v3, v13

    instance-of v14, v12, Lorg/apache/poi/hssf/record/chart/BeginRecord;

    if-eqz v14, :cond_1

    add-int/lit8 v5, v5, 0x1

    goto :goto_2

    :cond_1
    instance-of v14, v12, Lorg/apache/poi/hssf/record/chart/EndRecord;

    if-eqz v14, :cond_4

    add-int/lit8 v5, v5, -0x1

    if-ne v8, v5, :cond_3

    if-nez v6, :cond_2

    invoke-virtual {v0, v12}, Ljava/util/ArrayList;->add(Ljava/lang/Object;)Z

    move v10, v3

    move v8, v4

    move v6, v13

    goto :goto_1

    :cond_2
    move v10, v3

    move v8, v4

    :cond_3
    :goto_1
    if-ne v11, v5, :cond_4

    goto :goto_4

    :cond_4
    :goto_2
    instance-of v13, v12, Lorg/apache/poi/hssf/record/chart/ChartRecord;

    if-eqz v13, :cond_5

    iget-object v13, p0, Lorg/apache/poi/hssf/usermodel/HSSFChart;->chartRecord:Lorg/apache/poi/hssf/record/chart/ChartRecord;

    if-ne v12, v13, :cond_6

    move v9, v3

    move v11, v5

    goto :goto_3

    :cond_5
    instance-of v13, v12, Lorg/apache/poi/hssf/record/chart/SeriesRecord;

    if-eqz v13, :cond_6

    if-eq v9, v4, :cond_6

    add-int/lit8 v7, v7, 0x1

    move v8, v5

    :cond_6
    :goto_3
    if-eq v8, v4, :cond_0

    if-nez v6, :cond_0

    invoke-virtual {v0, v12}, Ljava/util/ArrayList;->add(Ljava/lang/Object;)Z

    goto :goto_0

    :cond_7
    :goto_4
    const/4 v2, 0x0

    if-ne v10, v4, :cond_8

    return-object v2

    :cond_8
    add-int/2addr v10, v13

    new-instance v3, Ljava/util/ArrayList;

    invoke-direct {v3}, Ljava/util/ArrayList;-><init>()V

    invoke-virtual {v0}, Ljava/util/ArrayList;->iterator()Ljava/util/Iterator;

    move-result-object v0

    move-object v4, v2

    :cond_9
    :goto_5
    invoke-interface {v0}, Ljava/util/Iterator;->hasNext()Z

    move-result v5

    if-eqz v5, :cond_12

    invoke-interface {v0}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v5

    check-cast v5, Lorg/apache/poi/hssf/record/RecordBase;

    instance-of v6, v5, Lorg/apache/poi/hssf/record/chart/BeginRecord;

    if-eqz v6, :cond_a

    new-instance v5, Lorg/apache/poi/hssf/record/chart/BeginRecord;

    invoke-direct {v5}, Lorg/apache/poi/hssf/record/chart/BeginRecord;-><init>()V

    goto :goto_6

    :cond_a
    instance-of v6, v5, Lorg/apache/poi/hssf/record/chart/EndRecord;

    if-eqz v6, :cond_b

    new-instance v5, Lorg/apache/poi/hssf/record/chart/EndRecord;

    invoke-direct {v5}, Lorg/apache/poi/hssf/record/chart/EndRecord;-><init>()V

    goto :goto_6

    :cond_b
    instance-of v6, v5, Lorg/apache/poi/hssf/record/chart/SeriesRecord;

    if-eqz v6, :cond_c

    check-cast v5, Lorg/apache/poi/hssf/record/chart/SeriesRecord;

    invoke-virtual {v5}, Lorg/apache/poi/hssf/record/chart/SeriesRecord;->clone()Ljava/lang/Object;

    move-result-object v4

    move-object v5, v4

    check-cast v5, Lorg/apache/poi/hssf/record/chart/SeriesRecord;

    new-instance v4, Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFSeries;

    invoke-direct {v4, p0, v5}, Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFSeries;-><init>(Lorg/apache/poi/hssf/usermodel/HSSFChart;Lorg/apache/poi/hssf/record/chart/SeriesRecord;)V

    goto :goto_6

    :cond_c
    instance-of v6, v5, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;

    if-eqz v6, :cond_d

    check-cast v5, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;

    invoke-virtual {v5}, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;->clone()Ljava/lang/Object;

    move-result-object v5

    check-cast v5, Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;

    if-eqz v4, :cond_11

    invoke-virtual {v4, v5}, Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFSeries;->insertData(Lorg/apache/poi/hssf/record/chart/LinkedDataRecord;)V

    goto :goto_6

    :cond_d
    instance-of v6, v5, Lorg/apache/poi/hssf/record/chart/DataFormatRecord;

    if-eqz v6, :cond_e

    check-cast v5, Lorg/apache/poi/hssf/record/chart/DataFormatRecord;

    invoke-virtual {v5}, Lorg/apache/poi/hssf/record/chart/DataFormatRecord;->clone()Ljava/lang/Object;

    move-result-object v5

    check-cast v5, Lorg/apache/poi/hssf/record/chart/DataFormatRecord;

    int-to-short v6, v7

    invoke-virtual {v5, v6}, Lorg/apache/poi/hssf/record/chart/DataFormatRecord;->setSeriesIndex(S)V

    invoke-virtual {v5, v6}, Lorg/apache/poi/hssf/record/chart/DataFormatRecord;->setSeriesNumber(S)V

    goto :goto_6

    :cond_e
    instance-of v6, v5, Lorg/apache/poi/hssf/record/chart/SeriesTextRecord;

    if-eqz v6, :cond_f

    check-cast v5, Lorg/apache/poi/hssf/record/chart/SeriesTextRecord;

    invoke-virtual {v5}, Lorg/apache/poi/hssf/record/chart/SeriesTextRecord;->clone()Ljava/lang/Object;

    move-result-object v5

    check-cast v5, Lorg/apache/poi/hssf/record/chart/SeriesTextRecord;

    if-eqz v4, :cond_11

    invoke-virtual {v4, v5}, Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFSeries;->setSeriesTitleText(Lorg/apache/poi/hssf/record/chart/SeriesTextRecord;)V

    goto :goto_6

    :cond_f
    instance-of v6, v5, Lorg/apache/poi/hssf/record/Record;

    if-eqz v6, :cond_10

    check-cast v5, Lorg/apache/poi/hssf/record/Record;

    invoke-virtual {v5}, Lorg/apache/poi/hssf/record/Record;->clone()Ljava/lang/Object;

    move-result-object v5

    check-cast v5, Lorg/apache/poi/hssf/record/Record;

    goto :goto_6

    :cond_10
    move-object v5, v2

    :cond_11
    :goto_6
    if-eqz v5, :cond_9

    invoke-virtual {v3, v5}, Ljava/util/ArrayList;->add(Ljava/lang/Object;)Z

    goto :goto_5

    :cond_12
    if-nez v4, :cond_13

    return-object v2

    :cond_13
    invoke-virtual {v3}, Ljava/util/ArrayList;->iterator()Ljava/util/Iterator;

    move-result-object p0

    :goto_7
    invoke-interface {p0}, Ljava/util/Iterator;->hasNext()Z

    move-result v0

    if-eqz v0, :cond_14

    invoke-interface {p0}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Lorg/apache/poi/hssf/record/RecordBase;

    add-int/lit8 v2, v10, 0x1

    invoke-interface {v1, v10, v0}, Ljava/util/List;->add(ILjava/lang/Object;)V

    move v10, v2

    goto :goto_7

    :cond_14
    return-object v4
.end method

.method public getChartHeight()I
    .locals 0

    iget-object p0, p0, Lorg/apache/poi/hssf/usermodel/HSSFChart;->chartRecord:Lorg/apache/poi/hssf/record/chart/ChartRecord;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/ChartRecord;->getHeight()I

    move-result p0

    return p0
.end method

.method public getChartTitle()Ljava/lang/String;
    .locals 0

    iget-object p0, p0, Lorg/apache/poi/hssf/usermodel/HSSFChart;->chartTitleText:Lorg/apache/poi/hssf/record/chart/SeriesTextRecord;

    if-eqz p0, :cond_0

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/SeriesTextRecord;->getText()Ljava/lang/String;

    move-result-object p0

    return-object p0

    :cond_0
    const/4 p0, 0x0

    return-object p0
.end method

.method public getChartWidth()I
    .locals 0

    iget-object p0, p0, Lorg/apache/poi/hssf/usermodel/HSSFChart;->chartRecord:Lorg/apache/poi/hssf/record/chart/ChartRecord;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/ChartRecord;->getWidth()I

    move-result p0

    return p0
.end method

.method public getChartX()I
    .locals 0

    iget-object p0, p0, Lorg/apache/poi/hssf/usermodel/HSSFChart;->chartRecord:Lorg/apache/poi/hssf/record/chart/ChartRecord;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/ChartRecord;->getX()I

    move-result p0

    return p0
.end method

.method public getChartY()I
    .locals 0

    iget-object p0, p0, Lorg/apache/poi/hssf/usermodel/HSSFChart;->chartRecord:Lorg/apache/poi/hssf/record/chart/ChartRecord;

    invoke-virtual {p0}, Lorg/apache/poi/hssf/record/chart/ChartRecord;->getY()I

    move-result p0

    return p0
.end method

.method public getSeries()[Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFSeries;
    .locals 1

    iget-object p0, p0, Lorg/apache/poi/hssf/usermodel/HSSFChart;->series:Ljava/util/List;

    invoke-interface {p0}, Ljava/util/List;->size()I

    move-result v0

    new-array v0, v0, [Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFSeries;

    invoke-interface {p0, v0}, Ljava/util/List;->toArray([Ljava/lang/Object;)[Ljava/lang/Object;

    move-result-object p0

    check-cast p0, [Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFSeries;

    return-object p0
.end method

.method public getType()Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFChartType;
    .locals 0

    iget-object p0, p0, Lorg/apache/poi/hssf/usermodel/HSSFChart;->type:Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFChartType;

    return-object p0
.end method

.method public removeSeries(Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFSeries;)Z
    .locals 13

    iget-object v0, p0, Lorg/apache/poi/hssf/usermodel/HSSFChart;->sheet:Lorg/apache/poi/hssf/usermodel/HSSFSheet;

    invoke-virtual {v0}, Lorg/apache/poi/hssf/usermodel/HSSFSheet;->getSheet()Lorg/apache/poi/hssf/model/InternalSheet;

    move-result-object v0

    invoke-virtual {v0}, Lorg/apache/poi/hssf/model/InternalSheet;->getRecords()Ljava/util/List;

    move-result-object v0

    invoke-interface {v0}, Ljava/util/List;->iterator()Ljava/util/Iterator;

    move-result-object v0

    const/4 v1, 0x0

    const/4 v2, -0x1

    move v3, v1

    move v5, v3

    move v6, v5

    move v7, v6

    move v4, v2

    move v8, v4

    move v9, v8

    :cond_0
    :goto_0
    invoke-interface {v0}, Ljava/util/Iterator;->hasNext()Z

    move-result v10

    if-eqz v10, :cond_9

    invoke-interface {v0}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v10

    check-cast v10, Lorg/apache/poi/hssf/record/RecordBase;

    instance-of v11, v10, Lorg/apache/poi/hssf/record/chart/BeginRecord;

    const/4 v12, 0x1

    if-eqz v11, :cond_1

    add-int/lit8 v3, v3, 0x1

    goto :goto_2

    :cond_1
    instance-of v11, v10, Lorg/apache/poi/hssf/record/chart/EndRecord;

    if-eqz v11, :cond_4

    add-int/lit8 v3, v3, -0x1

    if-ne v4, v3, :cond_3

    if-eqz v5, :cond_2

    invoke-interface {v0}, Ljava/util/Iterator;->remove()V

    move v5, v1

    move v4, v2

    move v7, v12

    goto :goto_1

    :cond_2
    move v4, v2

    :cond_3
    :goto_1
    if-ne v8, v3, :cond_4

    goto :goto_4

    :cond_4
    :goto_2
    instance-of v11, v10, Lorg/apache/poi/hssf/record/chart/ChartRecord;

    if-eqz v11, :cond_5

    iget-object v11, p0, Lorg/apache/poi/hssf/usermodel/HSSFChart;->chartRecord:Lorg/apache/poi/hssf/record/chart/ChartRecord;

    if-ne v10, v11, :cond_8

    move v8, v3

    move v6, v12

    goto :goto_3

    :cond_5
    instance-of v11, v10, Lorg/apache/poi/hssf/record/chart/SeriesRecord;

    if-eqz v11, :cond_7

    if-eqz v6, :cond_8

    invoke-static {p1}, Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFSeries;->access$200(Lorg/apache/poi/hssf/usermodel/HSSFChart$HSSFSeries;)Lorg/apache/poi/hssf/record/chart/SeriesRecord;

    move-result-object v11

    if-ne v11, v10, :cond_6

    move v4, v3

    move v5, v12

    goto :goto_3

    :cond_6
    add-int/lit8 v9, v9, 0x1

    goto :goto_3

    :cond_7
    instance-of v11, v10, Lorg/apache/poi/hssf/record/chart/DataFormatRecord;

    if-eqz v11, :cond_8

    if-eqz v6, :cond_8

    if-nez v5, :cond_8

    check-cast v10, Lorg/apache/poi/hssf/record/chart/DataFormatRecord;

    int-to-short v11, v9

    invoke-virtual {v10, v11}, Lorg/apache/poi/hssf/record/chart/DataFormatRecord;->setSeriesIndex(S)V

    invoke-virtual {v10, v11}, Lorg/apache/poi/hssf/record/chart/DataFormatRecord;->setSeriesNumber(S)V

    :cond_8
    :goto_3
    if-eqz v5, :cond_0

    invoke-interface {v0}, Ljava/util/Iterator;->remove()V

    goto :goto_0

    :cond_9
    :goto_4
    return v7
.end method

.method public setChartHeight(I)V
    .locals 0

    iget-object p0, p0, Lorg/apache/poi/hssf/usermodel/HSSFChart;->chartRecord:Lorg/apache/poi/hssf/record/chart/ChartRecord;

    invoke-virtual {p0, p1}, Lorg/apache/poi/hssf/record/chart/ChartRecord;->setHeight(I)V

    return-void
.end method

.method public setChartTitle(Ljava/lang/String;)V
    .locals 0

    iget-object p0, p0, Lorg/apache/poi/hssf/usermodel/HSSFChart;->chartTitleText:Lorg/apache/poi/hssf/record/chart/SeriesTextRecord;

    if-eqz p0, :cond_0

    invoke-virtual {p0, p1}, Lorg/apache/poi/hssf/record/chart/SeriesTextRecord;->setText(Ljava/lang/String;)V

    return-void

    :cond_0
    new-instance p0, Ljava/lang/IllegalStateException;

    const-string p1, "No chart title found to change"

    invoke-direct {p0, p1}, Ljava/lang/IllegalStateException;-><init>(Ljava/lang/String;)V

    throw p0
.end method

.method public setChartWidth(I)V
    .locals 0

    iget-object p0, p0, Lorg/apache/poi/hssf/usermodel/HSSFChart;->chartRecord:Lorg/apache/poi/hssf/record/chart/ChartRecord;

    invoke-virtual {p0, p1}, Lorg/apache/poi/hssf/record/chart/ChartRecord;->setWidth(I)V

    return-void
.end method

.method public setChartX(I)V
    .locals 0

    iget-object p0, p0, Lorg/apache/poi/hssf/usermodel/HSSFChart;->chartRecord:Lorg/apache/poi/hssf/record/chart/ChartRecord;

    invoke-virtual {p0, p1}, Lorg/apache/poi/hssf/record/chart/ChartRecord;->setX(I)V

    return-void
.end method

.method public setChartY(I)V
    .locals 0

    iget-object p0, p0, Lorg/apache/poi/hssf/usermodel/HSSFChart;->chartRecord:Lorg/apache/poi/hssf/record/chart/ChartRecord;

    invoke-virtual {p0, p1}, Lorg/apache/poi/hssf/record/chart/ChartRecord;->setY(I)V

    return-void
.end method

.method public setValueRange(ILjava/lang/Double;Ljava/lang/Double;Ljava/lang/Double;Ljava/lang/Double;)V
    .locals 0

    iget-object p0, p0, Lorg/apache/poi/hssf/usermodel/HSSFChart;->valueRanges:Ljava/util/List;

    invoke-interface {p0, p1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object p0

    check-cast p0, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;

    if-nez p0, :cond_0

    return-void

    :cond_0
    if-eqz p2, :cond_1

    invoke-virtual {p2}, Ljava/lang/Double;->isNaN()Z

    move-result p1

    invoke-virtual {p0, p1}, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;->setAutomaticMinimum(Z)V

    invoke-virtual {p2}, Ljava/lang/Double;->doubleValue()D

    move-result-wide p1

    invoke-virtual {p0, p1, p2}, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;->setMinimumAxisValue(D)V

    :cond_1
    if-eqz p3, :cond_2

    invoke-virtual {p3}, Ljava/lang/Double;->isNaN()Z

    move-result p1

    invoke-virtual {p0, p1}, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;->setAutomaticMaximum(Z)V

    invoke-virtual {p3}, Ljava/lang/Double;->doubleValue()D

    move-result-wide p1

    invoke-virtual {p0, p1, p2}, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;->setMaximumAxisValue(D)V

    :cond_2
    if-eqz p4, :cond_3

    invoke-virtual {p4}, Ljava/lang/Double;->isNaN()Z

    move-result p1

    invoke-virtual {p0, p1}, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;->setAutomaticMajor(Z)V

    invoke-virtual {p4}, Ljava/lang/Double;->doubleValue()D

    move-result-wide p1

    invoke-virtual {p0, p1, p2}, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;->setMajorIncrement(D)V

    :cond_3
    if-eqz p5, :cond_4

    invoke-virtual {p5}, Ljava/lang/Double;->isNaN()Z

    move-result p1

    invoke-virtual {p0, p1}, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;->setAutomaticMinor(Z)V

    invoke-virtual {p5}, Ljava/lang/Double;->doubleValue()D

    move-result-wide p1

    invoke-virtual {p0, p1, p2}, Lorg/apache/poi/hssf/record/chart/ValueRangeRecord;->setMinorIncrement(D)V

    :cond_4
    return-void
.end method
